### ISSUE TITLE
Оплата с формированием платежных данных на сервере

### ISSUE THREAD

**Issue by Vanchel** [Progressive-Mobile/tinkoff_sdk#13]
Нативные SDK для [iOS][iOS payment flow] и [Android][Android payment id] позволяют инициировать оплату на сервере, а в мобильном клиенте уже только завершить ее с полученным payment id. В этом пакете есть [`PaymentFlow`][PaymentFlow] как раз для такого сценария, но, как я понял, он используется только для оплаты с использованием динамических QR-кодов.

Подскажите, пожалуйста, есть ли возможность уже сейчас при помощи этого пакета осуществить стандартную оплату, инициализированную на сервере? Если нет, планируется ли поддержать такую возможность?

[iOS payment flow]: https://opensource.tinkoff.ru/tinkoff-mobile-tech/tinkoff-asdk-ios#%D1%81%D0%BE%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%B6%D0%B5%D0%B9
[Android payment id]: https://opensource.tinkoff.ru/tinkoff-mobile-tech/tinkoff-asdk-android#%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D0%B0-%D1%81-%D1%81%D1%83%D1%89%D0%B5%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%89%D0%B8%D0%BC-paymentid
[PaymentFlow]: https://github.com/Progressive-Mobile/tinkoff_sdk/blob/3a16393be375e57e00f3c595303ca3b0e635792d/lib/src/models/options/payment_flow.dart

**Comment by seosea0** [comment]
Добрый день! Мы выпустили новую версию плагина 0.6.0 и добавили в ней возможность завершать платеж в приложении. Вся необходимая информация и примеры находится в readme.
Если у Вас возникнут какие-нибудь проблемы с таким флоу, пожалуйста, дайте нам знать.
