### ISSUE TITLE
Декомпиляция приложения

### ISSUE THREAD

**Issue by brandshopru** [Progressive-Mobile/tinkoff_sdk#3]
Если декомпилировать приложение, то получится у злоумышленника будет логин, пароль и сертификат для запросов к api?

**Comment by jQwout** [comment]
Здравствуйте, как я вижу - ваше решение подразумевает хранение пароля в сдк. 
К сожалению, это решение имеет риски. сейчас в нативных решениях отказались от такого подхода, и вынесли генерацию токенам на бек системы.
подробнее о проблемах и решениям можно почитать тут , обратите внимание на последний коментарий.

https://github.com/tinkoff-mobile-tech/AcquiringSdkAndroid/issues/14

**Comment by evkorm** [comment]
здравствуйте! 
спасибо за правильные вопросы и замечания. будем разбираться.
