### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by VladilenC** [Progressive-Mobile/tinkoff_sdk#4]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':tinkoff_sdk' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by VladilenC** [comment]
Добрый день.
Измените, пожалуйста, версию Gradle plugin на 1.5.20.

**Comment by evkorm** [comment]
kotlin gradle plugin обновлен до версии 1.9.22.
