### ISSUE TITLE
Планируется ли обновление плагина до актуальных версий SDK Tinkoff ?

### ISSUE THREAD

**Issue by itopt** [Progressive-Mobile/tinkoff_sdk#5]

**Comment by evkorm** [comment]
здравствуйте! прямо сейчас этим занимаемся. iOS уже актуализировали. Android - в процессе. есть небольшие проблемы. думаю, на следующей неделе появится обновление.

**Comment by itopt** [comment]
Спасибо, Вам большое!

**Comment by evkorm** [comment]
плагин обновлен: iOS - до 3.1.1; Android - до 3.0.2.
